### ISSUE TITLE
Detecting boxes only

### ISSUE THREAD

**Issue by ghost** [s3nh/pytorch-text-recognition#6]
How to only detect boxes without text recognition?

**Comment by s3nh** [comment]
CraftReader() is responsible for boxes detection only. 
There is multi functionality at the moment  and app.py does not provide boxes detect. 
I can provide flask app.py with only boxes detection.

**Comment by ghost** [comment]
@s3nh The script that only output the boxes `x1, y1, x2, y2, x3, y3, x4, y4`
